#!/usr/bin/perl

#
#   Copyright (C) 2014 Chitika Inc.
#
#   This file is a part of Cmr
#
#   Cmr is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use warnings;

use File::Basename qw(dirname);
use Cwd qw(abs_path);
use lib  dirname(abs_path(__FILE__))."/../lib";
use Cmr::StartupUtils ();

use NanoMsg::Raw;

sub verify_client;
sub fail_job;

my ($log, $config) = Cmr::StartupUtils::script_init({
    'description' => 'Receives messages from cmr components and publishes them',
    'config' => "/etc/cmr/config.ini",
    'no_lock' => 1,
});

my $s_caster_in = nn_socket(AF_SP, NN_PULL);
nn_bind($s_caster_in,  "$config->{'caster_in'}");
nn_setsockopt($s_caster_in, NN_SOL_SOCKET, NN_RCVBUF, 16*1024*1024);

my $s_caster_out = nn_socket(AF_SP, NN_PUB);
nn_bind($s_caster_out, "$config->{'caster_out'}");
nn_setsockopt($s_caster_out, NN_SOL_SOCKET, NN_SNDBUF, 4*1024*1024);

while(! Cmr::StartupUtils::finished()) {
  Cmr::StartupUtils::load_config(\$config);

  # Receive broadcast events!
  nn_recv($s_caster_in, my $comp, 262143);

  # Broadcast events!
  nn_send($s_caster_out, $comp);
  $comp = undef;
}

