#!/usr/bin/perl

#
#   Copyright (C) 2014 Chitika Inc.
#
#   This file is a part of Cmr
#
#   Cmr is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use warnings;
use File::Basename qw(dirname);
use Cwd qw(abs_path);
use lib  dirname(abs_path(__FILE__))."/../lib";

use Cmr::JsonUtils ();

binmode STDIN,  ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';
use open ':utf8';

unless (@ARGV) {
    # PASSTHROUGH
    while (<STDIN>) {
        print "$_\n";
    }
    exit(0);
}

my @params = Cmr::JsonUtils::PathSplit(@ARGV);

while (<STDIN>) {
    chomp($_);
    if (/^[\{\[]/o) {
        if (/^\{/o && not /\"$params[0]->[0]\"/o) {
            print "\n";
            next;
        }
        my $json = Cmr::JsonUtils::Decode($_);
        unless ($json) {
            print "$_\n";
            next;
        }
        my $value = Cmr::JsonUtils::GetField($params[0], $json) // "";
        $value = Cmr::JsonUtils::Encode($value) if (ref($value));
        print "${value}\n";
    } else {
        print "$_\n";
    }
}

