#!/usr/bin/perl

#
#   Copyright (C) 2014 Chitika Inc.
#
#   This file is a part of Cmr
#
#   Cmr is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use warnings;

binmode STDIN,  ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';
use open ':utf8';

use HTTP::Request::Common;
use Furl;

#my $furl = Furl->new() or die "failed to create furl object\n";
my $furl = Furl->new(headers => ['Accept-Encoding' => 'gzip,deflate', 'Connection' => 'close']) or die "failed to create furl object\n";

for my $arg (@ARGV) {

#    print STDERR "GET: ", $arg, "\n";
    my $res = $furl->get($arg);
#    print STDERR "STATUS: ", $res->status(), "\n";
    if ($res->status() == 200) {
        print $res->decoded_content();
    }
}
